site_name: NFPM
site_description: NFPM is Not FPM - a simple deb, rpm and apk packager written in Go
copyright: Made with ❤️ by GoReleaser contributors.
repo_name: goreleaser/nfpm
repo_url: https://github.com/goreleaser/nfpm
edit_uri: edit/master/www/docs/

theme:
  name: material
  language: en
  logo: static/avatar.png
  favicon: static/favicon.ico
  include_search_page: false
  search_index_only: true
  features:
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

plugins:
  # disable temporarely because its freezing the page
  - search:
      prebuild_index: python
      lang:
      - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/goreleaser
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/goreleaser

google_analytics:
  - UA-106198408-1
  - auto

nav:
- index.md
- install.md
- usage.md
- Command Line Reference:
    - nfpm: cmd/nfpm.md
    - nfpm init: cmd/nfpm_init.md
    - nfpm package: cmd/nfpm_package.md
    - nfpm completion: cmd/nfpm_completion.md
- configuration.md
- tips.md
- contributing.md
- sponsors.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
